Objetivo 0
JaimeGM96/RutasAutobuses pull request #1
Opened 2023-09-18 08:35 UTC by JaimeGM96

* [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?
Si, conozco casos de equipos de desarrollo que tienen dificultades para asignar tareas y poder llegar a tiempo a los plazos de entrega de proyectos.
* [ ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
Si, este gestor de tareas le es útil tanto a los jefes de equipos de desarrollo como a los programadores a los que se les asignan las tareas que tiene que realizar y tener una aplicación donde acceder cada uno para visualizar esos datos es fundamental.
* [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
Si, requiere de realizar cálculos para la generación y asignación de las tareas.
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [ ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
El usuario tendrá que introducir algunos datos como sus cursos o competencias.
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?
He seguido la lista de comprobación sin marcar ninguna casilla al tuntún. 👍🏼

2023-09-18 08:46 UTC, JJ requested changes
Por favor, trata de ceñirte a la clara y concisa descripción de un problema. Las posibles soluciones se irán perfilando a lo largo del desarrollo.

2023-09-18 08:46 UTC, JJ commented on README.md
> +En empresas de desarrollo con equipos grandes que abarcan diferentes áreas de la informática, puede llegar a ser complicado llevar a cabo el desarrollo de múltiples proyectos de programación al mismo
No estás especificando claramente el problema. ¿El problema es que no se puede hacer? "Llevar a cabo el desarrollo" no es suficientemente concreto como para describir un problema sobre el que se pueda trabajar.

2023-09-18 08:46 UTC, JJ commented on README.md
> +Para resolver el problema que se ha mencionado anteriormente, se propone desarrollar un software en la nube que se encargue de, en función a las diferentes competencias de los equipos de desarrollo y
No se pide la solución, salvo si hace falta alguna aclaración para el hecho de que se pueda hacer en la nube; en todo caso, aquí lo que estás haciendo es añadir algún detalle al problema, lo que deberías haber hecho en la descripción del problema.

2023-09-18 09:04 UTC, JaimeGM96 commented
He añadido más información a la descripción del problema.

2023-09-18 09:23 UTC, JJ approved these changes
Veo bastantes inconvenientes en esta descripción del problema.

1. Sigues sin especificar el problema claramente. No conozco ninguna empresa donde haya problemas para asignar tareas a desarrolladores. Ninguna tarea se deja sin hacer por esa razón. Si no es un problema real, cualquier solución que plantees es artificial, porque no tienes una base para comparar si se ha resuelto el problema o se ha resuelto el problema mejor
2. No conozco ninguna empresa que asigne "perfiles" a programadores, salvo en el momento de contratarlos, e incluso cuando ya están trabajando, es habitualmente el propio desarrollador el que escoge las tareas con las que va a trabajar de las que haya en el actual *sprint*
3. Sigues proponiendo una solución, asignación de acuerdo con "perfil". Ni conozco ningún sistema que "perfile" a los desarrolladores (¿de acuerdo a qué? Salvo el lenguaje o lenguajes de programación o frameworks que manejen, en cuyo caso es trivial, no hay nada) ni que perfile las tareas, más alla de calificarlas como "bug", "refactorización", "feature" o algo así.
4. Finalmente, para los "perfiles" que hablas tendrías que tener un conocimiento personal de qué tipo de cosas entran en el perfil, en el sentido de usar datos reales (extraídos de alguna plataforma tipo Jira)

En resumen, lo que se pide en la asignatura es que pienses en un problema real del que tengas conocimientos suficientes para modelizarlo y para obtener datos reales para poder testearlo de forma que se pueda decir, de forma más o menos razonable, que *realmente* se está intentando resolver el problema.

2023-09-18 09:24 UTC, JJ requested changes
Perdón, he puesto aprobar pero no es así. Por favor, trata de elaborar el problema de forma que sea adecuado para la asignatura. En la primera sesión planteamos un juego de rol, si puedes buscar a una persona con el que hacerlo estaría bien, o si no el próximo día en clase.

2023-09-18 10:48 UTC, JaimeGM96 commented
He generalizado demasiado quizá, no me refiero a que todas las empresas de desarrollo tengan ese problema, hablo por mi experiencia personal y por la de amigos que trabajan en otras empresas. El perfil de programador si que lo he visto, aunque he visto más el perfil de otro tipo de experto en el mismo sector, asignando diferentes niveles según sus competencias. Lo quería extrapolar a mi problema. También en mi experiencia y en experiencia de amigos son los jefes de desarrollo o de equipo los que asignan tareas. Entiendo que éste no es el ideal de metodología de desarrollo ágil pero se dan casos reales de que no se siguen a raja tabla metodologías como scrum. Con perfilar a los programadores se me ocurren varias formas, no solo por su dominio en el lenguaje/framework, si no por sus aportaciones previas a diferentes desarrollos. Por ejemplo un programador en Laravel puede ser más experto que otro en el manejo de eventos, jobs, etc.

Por lo tanto tendría que decir algunas empresas de programación/departamentos de desarrollo en empresas que no son de programación. Tampoco debería de decir grandes departamentos de desarrollo, mi experiencia no es con equipos grandes, fallo mío.

Igualmente voy a buscar otro problema a resolver que esté más claro.

2023-09-20 08:40 UTC, JaimeGM96 commented
He cambiado el problema a uno diferente. Está listo para revisarlo.

2023-09-20 08:48 UTC, JJ requested changes
Del fichero de [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md)

> Crear problemas demasiado vagos ("una persona quiere invertir") o simplemente descritos como tales ("el problema del transporte").

También:

> Descripciones de problemas difíciles de comprender, lo que normalmente es consecuencia de una baja empatía; no te has colocado en la piel del cliente para entender qué quiere hacer y qué problema tiene.

De hecho, ni siquiera se ha identificado el cliente. 

Adicionalmente, otro error frecuente:

> No poner [IV-23-34] en el título del PR, lo que me hace imposible entre todos los mensajes de repos de GitHub, saber cuales son nuevas peticiones de revisión.

Así mismo, en [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) dice:

> La metodología denominada [design thinking](https://jj.github.io/IV/preso/design-thinking.html) te da una serie de pasos para poder entender posibles contextos en los cuales existe un problema, definirlo y proponer posibles soluciones.

En esta asignatura se trata de que se aprenda a aplicar una serie de metodologías que consisten las mejores prácticas en el tema. Puedes encontrar el cliente y problema sin usarla, simplemente por una buena intuición y lectura *muy* atenta del guión. Pero sin una metodología, *design thinking* o la que sea, es muy complicado hacerlo.

Como habrás visto en el guión de la clase de mañana, vamos a repetir el juego de rol. Te animo a que participes en clase, o bien sigas la metodología por tu cuenta (esa u otra)

2023-09-20 10:28 UTC, JaimeGM96 commented
No entiendo porque el problema es demasiado vago. Hablo del problema de la contaminación en las ciudades, que principalmente es causado por los vehículos. No he puesto referencia al [plan de bajas emisiones del ayuntamiento](https://www.autofacil.es/movilidad/restricciones-de-trafico/granada-zona-de-bajas-emisiones/546511.html) que se aplica por la [Ley del Cambio Climático y Transición Energética](https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-8447), ¿debería ponerlo?. En todo caso, expongo el problema y que además del plan de acción del ayuntamiento que hará que vehículos privados contaminantes no puedan acceder al centro, el resto de vehículos que circulan son los de transporte público. En mi caso me centro en los autobuses. ¿Tengo que poner al dueño de ALSA como usuario objetivo además de los dueños de otras empresas de transporte?

Espero que me aclare las dudas, gracias.

2023-09-20 11:52 UTC, JJ commented
> No entiendo porque el problema es demasiado vago. Hablo del problema de la contaminación en las ciudades, que principalmente es causado por los vehículos. No he puesto referencia al [plan de bajas emisiones del ayuntamiento](https://www.autofacil.es/movilidad/restricciones-de-trafico/granada-zona-de-bajas-emisiones/546511.html) que se aplica por la [Ley del Cambio Climático y Transición Energética](https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-8447), ¿debería ponerlo?. En todo caso, expongo el problema y que además del plan de acción del ayuntamiento que hará que vehículos privados contaminantes no puedan acceder al centro, el resto de vehículos que circulan son los de transporte público. En mi caso me centro en los autobuses. ¿Tengo que poner al dueño de ALSA como usuario objetivo además de los dueños de otras empresas de transporte?
> 

Gracias por contestar. Trataré de aclarar las dudas que tengas para que puedas superar el objetivo.

Como en todas las etapas en un proyecto de ingeniería, hay que seguir una metodología precisa para superar esa etapa de forma que se pueda satisfacer las necesidades del cliente. Para ello, como es natural, hay que identificar primero al cliente. En ese sentido no "tienes que poner" nada. Tienes que aplicar una metodología para poder especificar claramente el problema de forma que se puedan abordar las fases siguientes de resolución del mismo, que como sabes se trata de establecer productos mínimamente viables e historias de usuario. Si lo deseas, puedes echar un vistazo [a dicho objetivo](http://jj.github.io/IV/documentos/proyecto/1.Planificacion), que, dado que se trata de un proyecto, continúa a este, y dime si con una descripción del problema tal como la que tú has escrito se puede llegar fácilmente a una historia de usuario.

También hemos hecho mucho énfasis en que se trate de problemas más o menos personales. No entiendo muy bien como "el problema de las emisiones" es un problema personal, más allá de que, como todos, tengamos que sufrirlo.

Te recuerdo una vez más que esta descripción del problema tiene que ser un punto de partida para el desarrollo de un producto. Por favor, mira en los [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md) este en concreto:

> Crear problemas demasiado vagos ("una persona quiere invertir") o simplemente descritos como tales ("el problema del transporte").

O este:

> Descripciones de problemas difíciles de comprender, lo que normalmente es consecuencia de una baja empatía; no te has colocado en la piel del cliente para entender qué quiere hacer y qué problema tiene.

Tal como lo has planteado, serviría como contexto quizás para un problema. Pero para que sea un problema resoluble dentro de esta asignatura, sería conveniente que particulizaras ese problema en un problema personal, entre los que podrían estar

* Identificar los niveles de contaminación locales para saber si se debe tomar el coche o no (en cuyo caso el problema sería extraer información de fuentes poco estructuradas).
* Procesar usando algún algoritmo los planes que has enlazado, de forma que se pueda extraer la estructura y alguna información específica sobre ellos.

... En general, tienes siempre que pensar en la *aplicación* que vas a realizar a la hora de explicar, en este objetivo, el problema. Como sabes, en clase hacemos un juego de rol para hacer este tipo de cosas, así que te animo a que asistas a alguna de las siguientes clases, donde lo repetiremos para las personas que todavía no hayan superado el objetivo 0.

2023-09-21 11:36 UTC, JaimeGM96 commented
He cambiado el problema, sigue siendo de los autobuses pero no de la contaminación. En este caso, me he centrado en el problema de los usuarios con la puntualidad o falta de información del estado del autobús que están esperando. El otro día me pasó que esperando al autobús, el letrero ponía que tardaba un minuto. Al llegar estaba fuera de servicio y tuve que esperar al siguiente. Más de una vez me ha pasado que he tenido que esperar al siguiente o los siguientes autobuses de la misma línea porque estaban llenos y no me abrían las puertas. 

La personalización más concreta del problema entiendo que tiene que ir descrita después en la historia de usuario del siguiente objetivo. ¿Es suficiente describir que los usuarios tienen el problema como lo he comentado en la descripción o se tiene que personalizar más desde el principio?

2023-09-21 11:47 UTC, JJ commented
> He cambiado el problema, sigue siendo de los autobuses pero no de la contaminación. En este caso, me he centrado en el problema de los usuarios con la puntualidad o falta de información del estado del autobús que están esperando. El otro día me pasó que esperando al autobús, el letrero ponía que tardaba un minuto. Al llegar estaba fuera de servicio y tuve que esperar al siguiente. Más de una vez me ha pasado que he tenido que esperar al siguiente o los siguientes autobuses de la misma línea porque estaban llenos y no me abrían las puertas.
> 
> La personalización más concreta del problema entiendo que tiene que ir descrita después en la historia de usuario del siguiente objetivo. ¿Es suficiente describir que los usuarios tienen el problema como lo he comentado en la descripción o se tiene que personalizar más desde el principio?

Tiene que especificarse lo suficiente para que se pueda dilucidar si el problema es adecuado para la asignatura o no.

2023-09-21 11:52 UTC, JJ requested changes
Creo que has hecho un esfuerzo para empatizar con los posibles usuarios y clientes. Desgraciadamente, dependes demasiado de datos externos (o que tengan que introducir los usuarios) para poder construir un problema en esta asignatura. También necesitarías datos sobre líneas y sobre paradas, que creo que antes se obtenía de un JSON que ponía la Rober, pero que ahora han quitado.
Si el transporte o la contaminación son los temas que te interesa, mira a ver si en los [datos del ayuntamiento de Granada](https://www.granada.org/inet/wambiente.nsf/opendata.htm) u otros datos enlazados desde el guión puedes encontrar datos poco estructurados (cuyo reto sea extraer y estructurar) o datos estructurados (en cuyo caso el reto sería procesar para predecir, por ejemplo)

2023-09-21 11:52 UTC, JJ commented on README.md
> +Las líneas de autobuses que pasan por zonas universitarias o zonas céntricas de la ciudad de Granada se llenan y en algunas ocasiones los autobuses no paran para recoger a más gente. Esto supone una
Gracias por volver a enviarlo de nuevo. Has hecho un esfuerzo en tratar de especificar claramente de qué problema se trata.

Desgraciadamente, [en el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) pone qué tipo de problemas son poco adecuados para esta asignatura:

> Todos los problemas que requieran entradas físicas; todos aquellos en los que el usuario o cliente tenga que introducir mucha información.

2023-09-21 11:52 UTC, JJ commented on README.md
> +El problema que tiene los usuarios del transporte en autobús urbano es la falta de información que se dispone del estado del autobús que están esperando y si van a poder subirse a él.
Eso parece evidente. Sin embargo, también en el guión enlazado anteriormente, dice qué tipo de proceso no sería adecuado para esta asignatura:ç

> [Los que incluyan palabras ] como “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

2023-09-21 14:47 UTC, JaimeGM96 commented
Creía que seguía existiendo una API donde recoger esos datos. He encontrado una de la [Red de Consorcios de Transporte de Andalucía](https://api.ctan.es/doc/) pero no me vale para lo que había pensado. Seguiré buscando alguna alternativa.

2023-09-21 15:15 UTC, JJ commented
> Creía que seguía existiendo una API donde recoger esos datos. He encontrado una de la [Red de Consorcios de Transporte de Andalucía](https://api.ctan.es/doc/) pero no me vale para lo que había pensado. Seguiré buscando alguna alternativa.

INcluso aunque haya un API, extraer información y ponerla a disposición, como dice el guión, tampoco añade mucho valor al cliente y no sirve para la asignatura, que pide qeu sea un problema propio y conocido precisamente para que datos y contexto estén fácilmente disponibles.

2023-09-27 06:33 UTC, JJ commented
¿Algún problema con esto? ¿Necesitas alguna aclaración?

2023-09-27 07:21 UTC, JaimeGM96 commented
No encuentro ningún problema donde haya datos poco estructurados. Sigo dando vueltas a ver qué puedo encontrar.

2023-09-27 07:38 UTC, JJ commented
Tienes esto https://www.granada.org/inet/calidadaire.nsf/aire.csv con la calidad del aire de Granada. No está demasiado estructurado. También puedes compararlo con los datos del sistema de vigilancia medioambiental de la junta (aunque debería ser el mismo). También comprobar si alguna hora faltan datos, o hacer un pequeño algoritmo para averiguar la calidad del aire en la hora siguiente.

2023-09-27 07:41 UTC, JJ commented
Estoy viendo también esta [API de la red de consorcios de transporte](http://api.ctan.es/doc/#api-Corredores-ObtieneBloquesCorredor) donde la información no viene muy estructurada que digamos (es una especie de conversión rara de una hoja a un JSON). Podías extraer datos de ahí para calcular rutas, por ejemplo, con transbordo, teniendo en cuenta las horas de cada uno.

2023-09-28 18:03 UTC, JaimeGM96 commented
He actualizado la descripción del problema quitando el foco en el autobús urbano y centrándome en los autobuses de la Red de consorcios de transporte. Como información personal, he cogido alguna vez estos autobuses y me ha parecido muy lioso y con poca información. Creo que, como todo, si te conoces una línea por haberla cogido varias veces sabes que paradas y opciones tienes, pero siendo usuario nuevo es complicado moverse en estos autobuses.

2023-09-29 05:34 UTC, JJ approved these changes
:+1: 
Entiendo que te vas a centrar en el procesamiento de información poco estructurada de los ficheros que hay en el portal de datos abiertos; pero quizás podrías haber sido un poco más preciso en la descripción del problema. Te agradecería que lo hicieras antes de fusionarlo. También te agradecería que consideraras la posibilidad de plantear un cálculo de ruta incluyendo trasbordos entre líneas del mismo consorcio (que habitualmente son gratis). En todo caso, puedes hacerlo como HU en el siguiente objetivo.

2023-10-02 07:02 UTC, merged

2024-03-03 17:15 UTC, Gdakgdak22 approved these changes