[IV-23-24] Objetivo 3
JaimeGM96/RutasAutobuses pull request #20
Opened 2023-11-20 15:17 UTC by JaimeGM96

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-11-22 19:18 UTC, Christianlr approved these changes
Hola @JaimeGM96! Según he estado mirando, `rust` no requiere un runtime en el sentido tradicional en el que algunos lenguajes de programación lo hacen. No sabía acerca de esto hasta que he revisado tu PR :sunglasses: . En cuanto a los criterios para la elección de las herramientas, creo que son correctos. Solo un punto que, en mi opinión, sería interesante. Hubiera sido buena idea que, en términos de eficiencia o rendimiento, se tenga un valor numérico que los respalde basaso en fuentes fiables, pero es solo una opinión. Por lo demás, considero que está bastante bien :+1: :wink:

2023-11-23 07:44 UTC, carlosservi commented
Buenas, me ha tocado ser revisor. He estado mirando tu trabajo y está bastante bien, ya que al usar el estándar del lenguaje es una garantia de que funcione correctamente y que sea eficiente. Lo único que te diría que es un poco mejorable es explicar en el readme un poco que gestores has elegido y una pincelada de la razón. Un saludo

2023-11-26 09:12 UTC, JaimeGM96 commented
Hola chicos! Gracias por vuestros comentarios. Tienes razón @carlosservi, lo primero que podemos ver cuando entramos en el repositorio es el README.md y, si están las cosas resumidas, dará una idea a cualquiera que entre de qué va el proyecto y qué decisiones y medidas se han ido tomando. Me pongo a escribir las mejoras!

2023-11-28 17:23 UTC, JaimeGM96 commented
Después del cambio que ha comentado @carlosservi, está listo para que lo revise @jj.

2023-11-28 18:44 UTC, JJ requested changes
Gracias @carlosservi por la revisión; está casi completo, pero faltan un par de detalles.

2023-11-28 18:44 UTC, JJ commented on README.md
> +cargo check check
Esto no creo que sea así, @JaimeGM96 . Si lo que está mal es el comando en el `iv.yaml` por favor, corrígelo.

2023-11-28 18:44 UTC, JJ commented on docs/gestor-tareas.md
> +### [Cargo-make](https://sagiegurari.github.io/cargo-make/)
make lo puedes usar con cualquier lenguage también. Y otros generales, como `task`. Por favor, amplía un poco la búsqueda para incluir algunos de ese tipo.

2023-11-28 21:16 UTC, JaimeGM96 commented on README.md
> +cargo check check
Lo tenía con cargo check al principio pero me dió un fallo en los tests al hacer el pull request del enlace de este objetivo. A mi también me resultó raro.

2023-11-28 21:34 UTC, JaimeGM96 commented on docs/gestor-tareas.md
> +### [Cargo-make](https://sagiegurari.github.io/cargo-make/)
Me pongo a investigar más sobre ellos y actualizo la documentación.

2023-11-29 15:51 UTC, carlosservi approved these changes

2023-11-29 16:42 UTC, JaimeGM96 commented
Después de investigar sobre otros gestores de tareas, he incluido make en la documentación y he corregido el comando de check @JJ.

2023-11-29 16:48 UTC, JJ approved these changes
:+1:

2023-11-29 16:48 UTC, JJ commented on docs/gestor-tareas.md
> +### [Cargo-make](https://sagiegurari.github.io/cargo-make/)
Por favor, deja resueltos todos los comentarios con el commit en el que lo has hecho antes de mergear (y si es posible, antes de pedir revisión)

2023-11-29 16:48 UTC, JJ commented
Por favor, ponte con el objetivo 4 lo antes posible.

2023-11-29 16:50 UTC, merged