[IV-23-24] Objetivo 4
JaimeGM96/RutasAutobuses pull request #23
Opened 2023-12-02 10:49 UTC by JaimeGM96

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [x]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [x] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [x] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [x] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [x] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [x]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [x] ¿Se han testeado también las excepciones?

closes #22 #24 #26 #27

2023-12-22 08:05 UTC, migueruiz requested changes
Hola seré tu revisor! He estado leyendo tu objetivo, y creo que deberías de fijarte si los commits siguen las buenas practicas, deberías añadir aparte una pequeña descripción en la cual especificas que has hecho dentro del fichero.

2023-12-22 08:05 UTC, migueruiz commented on docs/herramienta-testing.md
> +### Elección
Me parece una opción óptima según tus criterios, pero quizás haya más opciones (contando con mi desconocimiento en  RUST), podrías darle un vistazo más, por si hay algún otro que te interesa!! 😄

2023-12-22 08:30 UTC, JaimeGM96 commented
> Hola seré tu revisor! He estado leyendo tu objetivo, y creo que deberías de fijarte si los commits siguen las buenas practicas, deberías añadir aparte una pequeña descripción en la cual especificas que has hecho dentro del fichero.

Hola, gracias por tu revisión! Hasta donde tengo entendido, los commits que escribo si siguen buenas prácticas. Al principio del commit pongo el prefijo para indicar que es lo que estoy haciendo: feat para agregar una nueva funcionalidad, test para agregar cosas relacionadas con tests, docs para documentación, etc. Después indico sobre que fichero se están agregando los cambios y por último la pequeña descripción de los cambios. Tengo entendido que no es necesario escribir una descripción más extensa siempre y cuando en el mesaje del commit esté toda la información necesaria.

2023-12-22 08:33 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +### Elección
Estuve buscando más opciones pero, al ser un lenguaje bastante reciente y el estándar ser una herramienta muy completa, no encontré mucho más. Seguiré echando un ojo por si me he saltado algo 👀

2023-12-24 13:30 UTC, marinajcs requested changes
Buenas, seré tu otra revisora para este objetivo. Espero que estas sugerencias te sirvan de
ayuda en la mayor medida de lo posible 😃

2023-12-24 13:30 UTC, marinajcs commented on tests/tests_ruta.rs
> +        assert_eq!(linea.id, 1);
En este test y los siguientes se están realizando comprobaciones de valores concretos en los asserts; es decir, el
éxito o fracaso del test depende de los datos utilizados. Para más información, puedes consultar este [comentario](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-4.md#sobre-los-tests)

2023-12-24 13:30 UTC, marinajcs commented on tests/tests_ruta.rs
> +        let linea = Linea {
Podría ser interesante el manejo de excepciones si, por ejemplo, se intenta crear una línea con id negativo,
paradas vacías u horarios inválidos. Por lo que he investigado, en Rust se utiliza el tipo de dato `Result<T,E>`
para la representación de errores ([ejemplo de uso](https://blog.vasquezruiz.me/manejo-de-errores-en-rust-una-introduccion-a-result/)).

2023-12-24 13:30 UTC, marinajcs commented on tests/tests_ruta.rs
> +        horarios.insert(101, vec![NaiveTime::from_hms(7, 0, 0)]);
Para ahorrar escribir líneas y modularizar más el código, es común colocar los datos de prueba en un archivo
separado y cargarlos en los tests cuando sea necesario.

2023-12-24 13:30 UTC, marinajcs commented on tests/tests_ruta.rs
> +        let rutas = buscador_rutas.encuentra(NaiveTime::from_hms(7, 0, 0), 101, 103);
Dado que en tu caso se encuentran todas las rutas posibles, independientemente de si son óptimas o no,
no es imprescindible una función de bondad que evalúe la calidad de las rutas encontradas, pero puede ser
interesante si, por ejemplo, se quisiera añadir la opción de ordenar la lista de rutas posibles en cuanto a
menor tiempo de viaje y/o cantidad de transbordos.

2023-12-24 13:30 UTC, marinajcs commented on docs/herramienta-testing.md
> +Para este proyecto, se va a hacer uso de BDD ya que, al describir los tests con lenguaje natural, resulta más sencillo cubrir todos los casos de uso y, por tanto, se consigue una mayor cobertura de t
En cierto modo, se están usando ambas metodologías mencionadas, puesto que TDD solo determina cuándo se
escriben los tests (antes de la implementación del código) y BDD, el tipo de aserciones a utilizar.

2023-12-26 16:36 UTC, JaimeGM96 commented
> Buenas, seré tu otra revisora para este objetivo. Espero que estas sugerencias te sirvan de ayuda en la mayor medida de lo posible 😃

Hola! Encantado y gracias por revisar mi PR 😄

2023-12-26 16:54 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        let linea = Linea {
Tengo implementadas las excepciones en las funciones que aplican la lógica de negocio con el operador ?. Por lo que tengo entendido, este operador hace que si se encuentra algún dato con el que no pueda continuar la ejecución correcta devuelve un error. Lo implementaré también para los casos que me comentas!

2023-12-26 16:58 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        assert_eq!(linea.id, 1);
Entiendo. En mi caso, debería de comprobar que tengo una ruta cuando realizo la consulta ¿no?

2023-12-26 16:59 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        horarios.insert(101, vec![NaiveTime::from_hms(7, 0, 0)]);
Me parece bien. Me pongo con ello!

2023-12-26 17:02 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +Para este proyecto, se va a hacer uso de BDD ya que, al describir los tests con lenguaje natural, resulta más sencillo cubrir todos los casos de uso y, por tanto, se consigue una mayor cobertura de t
Pero, por lo que había entendido, BDD comparte el principio de escribir los tests primero pero se centra en la forma de representar esos tests para que sean comprensibles por cualquier persona que los lea, ¿no?.

2023-12-26 17:07 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        assert_eq!(linea.id, 1);
Como yo no tengo ahora mismo implementada la obtención de la ruta óptima, ¿qué se debería de comprobar? El milestone que estoy desarrollando es el de sacar los datos y estructurarlos de forma adecuada.

2023-12-26 17:09 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        let rutas = buscador_rutas.encuentra(NaiveTime::from_hms(7, 0, 0), 101, 103);
Pero, eso sería realmente la obtención de las rutas óptimas, de una forma u otra. Me devolvería otras posibles rutas pero las primeras serían las mejores.

2023-12-27 17:58 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        let linea = Linea {
He implementado las excepciones en el constructor de BuscadorRutas. Solo se puede implementar en los struct que tienen definidos constructores.

2023-12-28 12:50 UTC, marinajcs reviewed
Si este milestone se encarga de la extracción y estructura de datos, es verdad que
se puede dejar a un lado la optimización de rutas. El manejo de excepciones que has
añadido me parece correcto 😄 

Como recomendación, si usas los mismos valores en la creación de horarios, líneas y
paradas de prueba para varios tests, puedes declararlos fuera de las funciones una sola
vez y así ahorrar tener que crearlos múltiples veces.

Para el test que comprueba que el buscador de rutas las encuentra correctamente, yo
haría una función: `test_buscador_rutas(líneas, paradas, horaSalida, paradaInicial, paradaDestino)` . Esta se encargaría de:

1. Crear el buscador con las líneas y paradas proporcionadas
2. Usar el método `encuentra` para extraer las rutas_encontradas para la hora y paradas especificadas
4. Verificar que `!rutas_encontradas.is_empty()`
5. Para cada ruta encontrada, otras validaciones adicionales como comprobar que la
primera parada coincida con `paradaInicial` y la última con `paradaDestino`, que las horas
de los transbordos sigan un orden lógico...

2023-12-28 13:05 UTC, marinajcs approved these changes
Lo anterior son sugerencias para evitar repetir código (de creación de líneas, paradas...)
y mejorar la flexibilidad al pasar los datos como parámetros a las funciones de prueba;
sin embargo, en general me parece que está bien 👍

2023-12-28 18:31 UTC, migueruiz approved these changes

2024-01-02 07:25 UTC, JJ commented
¿Listo para revisar?

2024-01-02 08:24 UTC, JaimeGM96 commented
Listo para revisar @JJ.

2024-01-02 09:03 UTC, JJ requested changes
Por favor, haz caso y en su caso resuelve los comentarios de @marinajcs y @migueruiz . No hace falta que te diga que queda muy poco tiempo para la evaluación y deberías hacerlo lo antes posible.

2024-01-02 09:03 UTC, JJ commented on docs/herramienta-testing.md
> +Para este proyecto, se va a hacer uso de BDD ya que, al describir los tests con lenguaje natural, resulta más sencillo cubrir todos los casos de uso y, por tanto, se consigue una mayor cobertura de t
Primero, debes cerrar todos los comentarios.
Segundo, @marinajcs tiene razón, y en todo caso, la metodología que uses es útil a la hora de documentar las elecciones. ¿Crees que enunciarla aquí ayuda a que se entienda cómo has superado el objetivo?

2024-01-02 09:03 UTC, JJ commented on docs/herramienta-testing.md
> +### Elección
Igual que arriba. Primero, tines que hacer algo sobre cualquier comentario: cambiar el texto o indicar en qué commit se ha cerrado. Cualquier comentario es una indicación válida por parte de las personas que lo han revisado, Y en este caso, no tienes más que mirar el apartado de testing de lib.rs para ver que hay bastantes más opciones, como indica @migueruiz

2024-01-02 09:03 UTC, JJ commented on tests/tests_ruta.rs
> +        let linea = Linea {
Indica entonces en qué commit se ha solucionaro y resuelve este comentario.

2024-01-02 09:03 UTC, JJ commented on tests/tests_ruta.rs
> +        horarios.insert(101, vec![NaiveTime::from_hms(7, 0, 0)]);
Aparentemente no lo has hecho, ¿no?

2024-01-02 11:03 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +### Elección
Resuelto en 0e36283e90284195e791c78d6daee45f6ef538ad

2024-01-02 11:11 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        let linea = Linea {
Resuelto en 845130b8d779fd1be032b97b90e7a2ebe1e964e0

2024-01-02 11:50 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        horarios.insert(101, vec![NaiveTime::from_hms(7, 0, 0)]);
Todavía no, tenía pensado almacenar los datos de la API pero no hay una forma rápida de descargarlos.

2024-01-02 12:03 UTC, JJ commented on tests/tests_ruta.rs
> +        horarios.insert(101, vec![NaiveTime::from_hms(7, 0, 0)]);
Simplemente pon los datos que estás usando en un fichero CSV o como más fácilmente se lea en Rust. Con "los datos de prueba" entiendo que @marinajcs se refiere a los dos argumentos que se pasan a `insert`, y que haces en varias ocasiones, en vez de usar un estructura de datos (recuperada de un fichero) y un bucle para recorrerla. DRY (don't repeat yourself) es una buena práctica que se debe usar en todo el código, pero especialmente en los tests, y si los tienes en un fichero externo, mucho mejor, porque es más fácil añadir nuevos casos de test según se necesiten.

2024-01-02 14:46 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +Para este proyecto, se va a hacer uso de BDD ya que, al describir los tests con lenguaje natural, resulta más sencillo cubrir todos los casos de uso y, por tanto, se consigue una mayor cobertura de t
¿Debería de, como esta puesto, mostrar cuales son las diferentes metodologías pero no indicar cual es la que uso ya que se hace uso de las dos?

2024-01-02 18:14 UTC, JJ commented on docs/herramienta-testing.md
> +Para este proyecto, se va a hacer uso de BDD ya que, al describir los tests con lenguaje natural, resulta más sencillo cubrir todos los casos de uso y, por tanto, se consigue una mayor cobertura de t
¿Te parece que el que muestres esto, repitiendo o parafraseando más o menos lo que dice en el guión, contribuye a que se entienda por qué has tomado una decisión sobre una herramienta u otra? En esta documentación conviene que incluyas sólo las herramientas consideradas y los criterios para decantarte por una u otra.

2024-01-02 19:28 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        horarios.insert(101, vec![NaiveTime::from_hms(7, 0, 0)]);
Resuelto en ee80e9de05c09bb8e52533f0cbe0b6d50e7f4c19

2024-01-02 19:32 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +Para este proyecto, se va a hacer uso de BDD ya que, al describir los tests con lenguaje natural, resulta más sencillo cubrir todos los casos de uso y, por tanto, se consigue una mayor cobertura de t
Resuelto en c047947c5643832e51a90f185c01867b83f90cfa

2024-01-02 19:32 UTC, JaimeGM96 commented
Corregidas todas las cosas que se han comentado. Listo para revisar @JJ.

2024-01-03 08:37 UTC, JJ requested changes
Aparte de lo comentado, en este objetivo se busca que los tests reflejen de la forma más clara posible las historias de usuario. No tengo muy claro dónde se testea #3 (que al ser la primera, supongo que es la que se está llevando a cabo, aunque el último issue que se refiere a ella se cerró en Octubre... en todo caso conviene que se entienda que los tests se tienen que desarrollar a partir de issues, y estos deben estar relacionados con las historias de usuario; estas no terminaron de desarrollarse en el objetivo 2)

2024-01-03 08:37 UTC, JJ commented on docs/herramienta-testing.md
> +Cargo dispone de su propio test runner. Como hemos visto antes, es la herramienta éstandar del lenguaje Rust para realizar tareas como la gestión de dependencias, la compilación del código, etc. Únic
Estás mezclando test runners con frameworks de test, y no examinando ni siquiera las bibliotecas de aserciones. Lo que se busca con este objetivo es que entendáis la diferencia entre los tres para empezar (aunque puede haber frameworks que incluyan los tres, lo que no parece el caso aquí), mostrando en la práctica que entendéis los conceptos correspondientes. ¿No has considerado establecer criterios, buscar y elegir herramientas en cada uno de los tres niveles, o bien un framework que incluya los tres?

2024-01-03 08:37 UTC, JJ commented on docs/herramienta-testing.md
> +### [Trybuild](https://lib.rs/crates/trybuild)
¿De qué forma tiene esto alguna relación con las herramientas que se tienen que elegir en este objetivo?

2024-01-03 08:37 UTC, JJ commented on docs/herramienta-testing.md
> +Proptest es un framework de testing que nos permite probar que, para entradas arbitrarias en nuestros tests, se cumplan ciertas propiedades. Está basado en el framework QuickCheck de Haskell y en Hyp
¿Puedes explicar de qué forma esta herramienta tiene algo que ver con lo que se tiene que usar en este objetivo, para este milestone en tu proyecto?

2024-01-03 08:37 UTC, JJ commented on docs/herramienta-testing.md
> +Por lo que se ha expuesto anteriormente, la herramienta de testing que se ha decidido usar es cargo-nextest ya que, además de cumplir con todos los criterios de selección como también lo hace Cargo,
Sólo has elegido un test runner de los tres niveles de herramientas que hay que elegir. Como ya se te ha indicado, que haya test runners y bibliotecas de aserciones en el lenguaje no elimina automáticamente la necesidad de examinar otras alternativas, porque lo que se busca, más allá de escribir tests específicamente en Rust, es que se comprendan los niveles de la "pirámide" de testing y que se comprenda como tomar decisiones y documentarlas.

2024-01-03 08:37 UTC, JJ commented on src/ruta.rs
> +			return Err("No se puede crear un buscador de rutas sin lineas");
En general, el diseño de las excepciones debía haber sido parte del objetivo 2; si no, siempre conviene crear excepciones específicas que se puedan capturar en otro nivel.

2024-01-03 08:37 UTC, JJ commented on tests/tests_ruta.rs
> +        let primera_parada = paradas_json[0].as_i64().unwrap();
Como se te ha indicado, debes evitar la repetición de código: DRY.

2024-01-04 17:14 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +Cargo dispone de su propio test runner. Como hemos visto antes, es la herramienta éstandar del lenguaje Rust para realizar tareas como la gestión de dependencias, la compilación del código, etc. Únic
Resuelto en bfa2fdbf705c341eb78a44c5ea5b72ab44f41697

2024-01-04 17:14 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +### [Trybuild](https://lib.rs/crates/trybuild)
Resuelto en bfa2fdbf705c341eb78a44c5ea5b72ab44f41697

2024-01-04 17:15 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +Proptest es un framework de testing que nos permite probar que, para entradas arbitrarias en nuestros tests, se cumplan ciertas propiedades. Está basado en el framework QuickCheck de Haskell y en Hyp
Resuelto en bfa2fdbf705c341eb78a44c5ea5b72ab44f41697

2024-01-04 17:15 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +Por lo que se ha expuesto anteriormente, la herramienta de testing que se ha decidido usar es cargo-nextest ya que, además de cumplir con todos los criterios de selección como también lo hace Cargo,
Resuelto en bfa2fdbf705c341eb78a44c5ea5b72ab44f41697

2024-01-04 17:28 UTC, JaimeGM96 commented on tests/tests_ruta.rs
> +        let primera_parada = paradas_json[0].as_i64().unwrap();
Resuelto en 6672069a7ddcac8321021c67863270cd8db093ca

2024-01-04 17:29 UTC, JaimeGM96 commented
Listo para revisar @JJ.

2024-01-04 18:46 UTC, JJ commented on src/ruta.rs
> +			return Err("No se puede crear un buscador de rutas sin lineas");
... Por favor, no te olvides de resolver todos los comentarios... Esta objeción no bloquea la consecución del objetivo, pero la no resolución de los comentarios puede hacerlo.

2024-01-04 18:53 UTC, JJ approved these changes
OK, todavía podría mejorar un poco, pero creo que ya a estas alturas el objetivo está superado. Si puedes hacer los cambios antes del siguiente PR, por favor hazlo; y recuerda resolver todos los comentarios.

2024-01-04 18:53 UTC, JJ commented on docs/herramienta-testing.md
> +Proptest es un framework de testing que nos permite probar que, para entradas arbitrarias en nuestros tests, se cumplan ciertas propiedades. Para ello, englobamos nuestros tests dentro de la sección
Me da la impresión, solo por nombre, que este framework hace "property testing", que no es exactamente unit testing. También hace *shrinking*, que es reducir al mínimo el caso de test para reproducir el problema. Me da la impresión de que son conceptos unp oco más avanzados de lo que se busca; pero también mirando al apartado `testing` de lib.rs que las bibliotecas de testing que hay para Rust son todos casos especiales. Podías haber mencionado, sin embargo [NTest](https://lib.rs/crates/ntest), que parece más tradicional, aunque no esté demasiado actualizada.

2024-01-04 18:53 UTC, JJ commented on iv.yaml
> +test: tests/tests_ruta.rs
Igual el nombre del fichero es un poco redundante, ¿no?

2024-01-06 17:30 UTC, JaimeGM96 commented on docs/herramienta-testing.md
> +Proptest es un framework de testing que nos permite probar que, para entradas arbitrarias en nuestros tests, se cumplan ciertas propiedades. Para ello, englobamos nuestros tests dentro de la sección
Estuve mirando a ver si encontraba más opciones pero sobretodo encontraba bibliotecas de aserciones para cosas muy concretas como aserciones para el sistema de ficheros, http, etc. Voy a mirar [NTest](https://lib.rs/crates/ntest) como comentas para ver que tal es 👍🏼.

2024-01-06 17:34 UTC, JaimeGM96 commented on iv.yaml
> +test: tests/tests_ruta.rs
Resuelto en 63b0fe56b7512721ecce65cd2095c3a02ed09d09

2024-01-06 17:39 UTC, JaimeGM96 commented on src/ruta.rs
> +			return Err("No se puede crear un buscador de rutas sin lineas");
No me había dado cuenta, lo siento. ¿A qué se refiere exactamente? ¿Tengo que definir en un issue cuales serán los casos en los que se deberían de producir excepciones?

2024-01-06 17:46 UTC, JJ commented on src/ruta.rs
> +			return Err("No se puede crear un buscador de rutas sin lineas");
Eso también, pero lo principal es que las excepciones no se crean para tirar una aplicación, sino para capturarlas a algún nivel y darle un error significativo al cliente; en esta asignatura el nivel en el que se tienen que capturar es el de las rutas REST, y tendrás que crear excepciones específicas que puedan convertirse en códigos de estado significativos que se puedan devolver al cliente.

2024-01-09 15:07 UTC, merged