[IV-23-24] Objetivo 5
JaimeGM96/RutasAutobuses pull request #29
Opened 2024-01-09 17:32 UTC by JaimeGM96

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2024-01-10 20:03 UTC, adelahera reviewed
Buenas, he echado un vistazo al objetivo y me ha gustado bastante. Sobre todo la justificación y elección de criterios creo que está muy completa. Sin embargo, te he dejado un par de comentarios de una cosilla que no se debe hacer. Puedes echar un vistazo a eso mismo en los errores comunes, que quizá está más completo. Te dejo el enlace [aquí.](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-5.md)

Ánimo!

2024-01-10 20:03 UTC, adelahera commented on Dockerfile
> +COPY Cargo.toml Cargo.lock ./
En el directorio donde se ejecutan los tests no debe haber copiado nada. Eso se debe hacer en el escritorio /app

2024-01-10 20:03 UTC, adelahera commented on Dockerfile
> +	&& ln -s /app/test/src /app/src
Esta parte creo que también sobra, pues como he dicho, en /app/test/ no debe haber nada. En esa ruta simplemente ejecuta los tests. No alojes los sources allí.

2024-01-11 05:59 UTC, JaimeGM96 commented on Dockerfile
> +COPY Cargo.toml Cargo.lock ./
Es necesario copiar el Cargo.toml y lock, hasta donde yo he comprobado, para instalar las dependencias necesarias cuando se construye la imagen de docker para poder ejecutar luego los tests con normalidad.

2024-01-11 06:07 UTC, JaimeGM96 commented on Dockerfile
> +	&& ln -s /app/test/src /app/src
Este es un pequeño truco que hay que hacer con Rust. Cargo necesita que haya un fichero de código para actualizar las dependencias. Si te fijas, hago un touch y lo dejo vacío para que al menos exista aunque no contenga nada. Posteriormente ese fichero se borra. Luego el enlace se usa para que Cargo tenga manera de encontrar el fichero lock. No se exactamente porque Cargo no es capaz de encontrarlo pero he hecho multitud de pruebas y me daba problemas de que no encontraba Cargo.lock y abortaba la ejecución. Después de mucho buscar, esta es la solución que ha hecho que funcione.

2024-01-11 06:08 UTC, JaimeGM96 commented
Hola @adelahera! Gracias por tu revisión. Coméntame que te parece lo que te he dejado en los comentarios que me habías puesto 😄

2024-01-11 10:41 UTC, adelahera commented on Dockerfile
> +	&& ln -s /app/test/src /app/src
Sobre esto, de Rust no entiendo mucho, pero te decía que sobra por lo mismo de antes. Como /app/test debe estar vacío, cuando accedas por el enlace simbólico te dará fallo, pues no existe la carpeta /src en /app/test.

2024-01-11 10:41 UTC, adelahera commented on Dockerfile
> +COPY Cargo.toml Cargo.lock ./
Sí, si sobre eso no cabe duda, por supuesto que es necesario. El problema es que no se debe copiar en el directorio donde se ejecutan los tests, compruébalo en los errores comunes que te he dejado en la revisión.

2024-01-11 10:59 UTC, JaimeGM96 commented on Dockerfile
> +	&& ln -s /app/test/src /app/src
Entiendo lo que quieres decir pero no he encontrado otra forma de engañar a Cargo para que instale las dependencias y funcione correctamente. Por lo que he investigado es un poco puñetero con docker.

2024-01-11 14:41 UTC, JaimeGM96 commented on Dockerfile
> +COPY Cargo.toml Cargo.lock ./
Vale vale, lo he entendido!

2024-01-11 14:41 UTC, JaimeGM96 commented on Dockerfile
> +COPY Cargo.toml Cargo.lock ./
Resuelto en 75e7ed8c615ef04f2e0cfad3367f3f6ba948fe32

2024-01-11 15:12 UTC, adelahera commented on Dockerfile
> +	&& ln -s /app/test/src /app/src
Entiendo. Yo he investigado un poco y he visto que sí que suele dar pequeños problemas.

2024-01-11 15:12 UTC, adelahera approved these changes

2024-01-11 15:45 UTC, JaimeGM96 commented
Listo para revisar @JJ

2024-01-11 16:20 UTC, JJ commented on Dockerfile
> +	&& ln -s /app/test/src /app/src
Otros años hubo que hacer trucos similares. Si mal no recuerdo, había incluso que copiar todos los fuentes al interior del contenedor. La solución, por otro lado, no incumple ninguna buena práctica. Es una ñapa totalmente legal.

2024-01-11 18:05 UTC, JaimeGM96 commented on Dockerfile
> +	&& ln -s /app/test/src /app/src
Entonces doy por resuelto este comentario 👍🏼

2024-01-11 19:07 UTC, JJ requested changes
Me temo que vas a tener que darle una pequeña vuelta a lo indicado, mejorar la justificación de la imagen elegida, y por supuesto ajustar la justificación a la que efectivamente has elegido, entendiendo claramente qué significan los tags de las imágenes de Docker.

2024-01-11 19:07 UTC, JJ commented on .gitignore
> +# Cargo.lock
Quizás tendría sentido que  quitaras también el comentario...

2024-01-11 19:07 UTC, JJ commented on Dockerfile
> +FROM rust:alpine3.19
¿Por qué usas una versión específica? Si no lo justificas más abajo, en general se debe tratar de usar la versión latest, salvo que haya vulnerabilidades no parcheadas en ella.

2024-01-11 19:07 UTC, JJ commented on .github/workflows/ci.yml
> +      - 'Cargo.toml'
No has incluido uno de los ficheros que *si* incluyes en el Dockerfile.

2024-01-11 19:07 UTC, JJ commented on Dockerfile
> +USER jaime
No es habitual que se use el nombre de la persona que mantiene como usuario del contenedor.

2024-01-11 19:07 UTC, JJ commented on docs/imagen-contenedor.md
> +Es la imágen oficial de Rust sobre Alpine Linux. Es una imagen muy ligera pero, de entre las opciones oficiales, es la que mayor tamaño tiene. Como podemos ver en docker hub, es la más segura de toda
En realidad, has escogido la versión 3.19, que es simplemente la primera que aparece en la búsqueda. Y no es cierto que tenga mayor tamaño, más bien al revés, ¿no?

2024-01-11 19:07 UTC, JJ commented on docs/imagen-contenedor.md
> +Es la imágen oficial de Rust sobre Debian Bullseye. Esta imagen es más ligera que la de Alpine pero al contrario que con la anterior, si se han encontrado vulnerabilidades.
Como unos 6 o 7 megas. No es diferencia.

2024-01-11 19:07 UTC, JJ commented on docs/imagen-contenedor.md
> +### [Rust-slim-buster](https://hub.docker.com/_/rust)
buster y bullseye son diferentes versiones de debian. Se deben escoger o mirar no por tamaño u otra razón, sino porque sean la última versión. De hecho, como he comentado en Alpine, salvo por razón de vulnerabilidades detectadas, se debe optar por la última versión de un SO.

2024-01-11 19:07 UTC, JJ commented on docs/imagen-contenedor.md
> +Es una imagen no oficial de Rust. Es la más pesada de todas ya que dispone de multitud de librerías que las otras no traen de serie.
Pueden ser librerías que use tu aplicación, y que al final van a hacer que tu imagen ocupe lo mismo.

2024-01-11 19:07 UTC, JJ commented on docs/imagen-contenedor.md
> +- **Eficiencia**: Necesitamos que la imagen que elijamos sea eficiente ya que, para poder subir cualquier cambio a producción, es necesario que la imagen se construya lo más rápido posible.
No es algo que hayas examinado en ninguna de las imágenes. Y precisamente en Rust, con lo que tarda la compilación, puede ser un factor importante, y puedes encontrar diferencias grandes entre las basadas en Alpine y las basadas en Debian.

2024-01-11 19:07 UTC, JJ commented on docs/imagen-contenedor.md
> +La imagen que se va a elegir es la de Alpine. Cumple con todos los criterios de selección y, aunque no sea la más ligera de todas, es mucho más segura que las demás.
A ver, la slim tiene 0H, 0M, 29L. Las L tampoco es que sean como para echarse las manos a la cabeza. Si las miras, muchas están en utilidades como `tar` o `perl` que tampoco son nada del otro jueves. Hay 2 en glibc que evidentemente no están en Alpine (porque no usa glibc), pero tampoco parece que puedan afectar seriamente a nada en Rust. Una es de 2010, así que tampoco debe ser tan grave...

2024-01-12 16:23 UTC, JaimeGM96 commented on .gitignore
> +# Cargo.lock
Resuelto en 75b9df069a20f9780fd4c22dee7adc214874f400

2024-01-12 16:24 UTC, JaimeGM96 commented on Dockerfile
> +FROM rust:alpine3.19
Resuelto en db560c2f62cc67887fe5cbec0353e052baafda05

2024-01-12 16:24 UTC, JaimeGM96 commented on .github/workflows/ci.yml
> +      - 'Cargo.toml'
Resuelto en 5bcf110377434f1dc53704ff22afcb62f8957b16

2024-01-12 16:24 UTC, JaimeGM96 commented on Dockerfile
> +USER jaime
Resuelto en 3f3a89bc92435c5c5e09bf269cab5ed1c5087ccd

2024-01-15 09:12 UTC, JJ commented
El periodo de evaluación ordinaria termina el día 17, a la hora de la presentación. Sería extremadamente conveniente que terminaras los cambios pronto, para poder revisarlo antes de esa fecha.

2024-01-15 17:41 UTC, JaimeGM96 commented on docs/imagen-contenedor.md
> +La imagen que se va a elegir es la de Alpine. Cumple con todos los criterios de selección y, aunque no sea la más ligera de todas, es mucho más segura que las demás.
Resuelto en 41eb6473f0960aa0a741f92f83ce8b2a3cfdf743

2024-01-15 17:41 UTC, JaimeGM96 commented on docs/imagen-contenedor.md
> +Es la imágen oficial de Rust sobre Alpine Linux. Es una imagen muy ligera pero, de entre las opciones oficiales, es la que mayor tamaño tiene. Como podemos ver en docker hub, es la más segura de toda
Resuelto en 41eb6473f0960aa0a741f92f83ce8b2a3cfdf743

2024-01-15 17:41 UTC, JaimeGM96 commented on docs/imagen-contenedor.md
> +Es la imágen oficial de Rust sobre Debian Bullseye. Esta imagen es más ligera que la de Alpine pero al contrario que con la anterior, si se han encontrado vulnerabilidades.
Resuelto en 41eb6473f0960aa0a741f92f83ce8b2a3cfdf743

2024-01-15 17:41 UTC, JaimeGM96 commented on docs/imagen-contenedor.md
> +### [Rust-slim-buster](https://hub.docker.com/_/rust)
Resuelto en 41eb6473f0960aa0a741f92f83ce8b2a3cfdf743

2024-01-15 17:41 UTC, JaimeGM96 commented on docs/imagen-contenedor.md
> +Es una imagen no oficial de Rust. Es la más pesada de todas ya que dispone de multitud de librerías que las otras no traen de serie.
Resuelto en 41eb6473f0960aa0a741f92f83ce8b2a3cfdf743

2024-01-15 17:41 UTC, JaimeGM96 commented on docs/imagen-contenedor.md
> +- **Eficiencia**: Necesitamos que la imagen que elijamos sea eficiente ya que, para poder subir cualquier cambio a producción, es necesario que la imagen se construya lo más rápido posible.
Resuelto en 41eb6473f0960aa0a741f92f83ce8b2a3cfdf743

2024-01-15 17:43 UTC, JaimeGM96 commented
He vuelto a probar las diferentes imágenes, esta vez anotando bien los resultados y documentando mejor la elección. Listo para revisar @JJ

2024-01-15 18:55 UTC, JJ approved these changes
:100: Enhorabuena

2024-01-17 18:34 UTC, merged